#!/bin/sh
#
# Script to remove unwanted crap from a fresh lubuntu installation. This includes a lot of the LXDE crap, as I use awesome WM (http://awesome.naquadah.org/)

sudo apt-get remove \
	abiword \
	abiword-common \
	abiword-plugin-grammar \
	abiword-plugin-mathview \
	ace-of-penguins \
	audacious \
	audacious-plugins \
	audacious-plugins-data \
	blueman \
	catfish \
	chromium-browser \
	chromium-browser-l10n \
	chromium-codecs-ffmpeg \
	galculator \
	gnumeric \
	gnumeric-common \
	gnumeric-doc \
	guvcview \
	hardinfo \
	leafpad \
	lightdm \
	lubuntu-lxpanel-icons \
	lubuntu-software-center \
	lxappearance \
	lxinput \
	lxkeymap \
	lxlauncher \
	lxmenu-data \
	lxpanel \
	lxpanel-indicator-applet-plugin \
	lxrandr \
	lxsession \
	lxsession-data \
	lxsession-edit \
	lxshortcut \
	lxtask \
	lxterminal \
	mtpaint \
	obconf \
	openbox \
	pidgin \
	pidgin-data \
	pidgin-libnotify \
	pidgin-microblog \
	sylpheed \
	sylpheed-doc \
	sylpheed-i18n \
	sylpheed-plugins \
	transmission \
	tsconf \
	wvdial \
	xfburn \
	xfce-keyboard-shortcuts \
	xfce4-notifyd \
	xfce4-power-manager \
	xfce4-power-manager-data \
	xfconf \
	xpad

# remove graphics drivers that don't make sense
sudo apt-get remove xserver-xorg-video-ati \
	xserver-xorg-video-cirrus \
	xserver-xorg-video-fbdev \
	xserver-xorg-video-mach64 \
	xserver-xorg-video-mga \
	xserver-xorg-video-neomagic \
	xserver-xorg-video-nouveau \
	xserver-xorg-video-openchrome \
	xserver-xorg-video-qxl \
	xserver-xorg-video-r128 \
	xserver-xorg-video-radeon \
	xserver-xorg-video-s3 \
	xserver-xorg-video-savage \
	xserver-xorg-video-siliconmotion \
	xserver-xorg-video-sis \
	xserver-xorg-video-sisusb \
	xserver-xorg-video-tdfx \
	xserver-xorg-video-trident

# remove unneeded dependencies
sudo apt-get --purge autoremove

# purge unneeded configs
dpkg --get-selections | grep deinstall | sed 's/deinstall/\lpurge/' | sudo dpkg --set-selections; sudo dpkg -Pa
